### PR TITLE
Added ability to customize job options in listeners

### PR DESCRIPTION
**Pull request by k-rudy**
Hey guys,

This PR adds support of custom job options when registering a listener.
In order to work it requires few changes in Wisper https://github.com/krisleech/wisper/pull/159. 

 It supports all existing configurations + adds ability to pass additional options via the following syntax:

```ruby
cancel_order.subscribe(OrderNotifier.new, async: { queue: 'custom', retry: false })
```

Decreased coverage is expected as one of the specs is suspended until `wisper` PR is merged

The build is failing expectedly, @krisleech you need to merge https://github.com/krisleech/wisper-activejob/pull/13 first that's waiting for your consideration for a while already.

Thanks,
Kon.

### CODE REVIEW

**Comment by shved** [comment]
@krisleech Hi kris! Just curious if you're going to merge it? @k-ruby could you please finish your contribution? It would be great!

**Comment by k-rudy** [comment]
@shved sure, my side is done more than a year ago and it just waits to be considered / merged by @krisleech.

**Comment by shved** [comment]
@k-rudy but what about CI checks? there's a test coverage decrease warning

**Comment by k-rudy** [comment]
> @k-rudy but what about CI checks? there's a test coverage decrease warning

@shved sure, but see comment about that in the description of the PR. Until  https://github.com/krisleech/wisper-activejob/pull/13 is merged this is expected

**Comment by j27lee** [comment]
> > @k-rudy but what about CI checks? there's a test coverage decrease warning
> 
> @shved sure, but see comment about that in the description of the PR. Until #13 is merged this is expected

@k-rudy #13 was merged July 28, 2017.  Can you update your PR to reinstate the skipped test please?

**Comment by k-rudy** [comment]
@j27lee I'd be happy to do it, but @krisleech closed my PR to wisper without merging - krisleech/wisper#159. That PR is a requirement in order for this PR to work.

**Comment by j27lee** [comment]
@k-rudy Ah... sorry... missed that!  Passing a `queue` option is critical for us to be able to use this.

**Comment by k-rudy** [comment]
> Passing a queue option is critical for us to be able to use this.

If that's an acceptable option for you I can suggest using ProFinda's fork that we maintain and that contains the fix

```
gem 'wisper', git: 'https://github.com/Profinda/wisper'
gem 'wisper-sidekiq', git: 'https://github.com/Profinda/wisper-sidekiq'
```

or for active job:

```
gem 'wisper', git: 'https://github.com/Profinda/wisper'
gem 'wisper-activejob', git: 'https://github.com/Profinda/wisper-activejob'
```

If something doesn't work for you, feel free to raise issues there

**Pull request closed without merging**
